import React, { useState } from "react";
import {
  BenefitPayButton,
  Edges,
  Locale,
} from "@tap-payments/benefit-pay-button";

export interface TapPaymentProps {
  // Payment details
  amount: string; // Amount to charge (e.g., "12.50")
  currency: string; // Currency code (e.g., "BHD", "USD", "SAR")
  
  // Event/Order details
  eventId?: string | number;
  orderId?: string; // Your internal order ID
  transactionId?: string; // Your internal transaction ID
  
  // Customer information
  customer?: {
    firstName: string;
    lastName: string;
    middleName?: string;
    email?: string;
    phone?: {
      countryCode: string; // e.g., "+20", "+966"
      number: string;
    };
  };
  
  // Metadata (optional custom data)
  metadata?: {
    udf1?: string;
    udf2?: string;
    udf3?: string;
    udf4?: string;
    udf5?: string;
  };
  
  // UI Configuration
  locale?: "en" | "ar"; // "en" or "ar" (maps to Locale.EN or Locale.AR)
  edges?: "curved" | "straight"; // "curved" or "straight" (maps to Edges.CURVED or Edges.STRAIGHT)
  debug?: boolean;
  
  // Callbacks
  onReady?: () => void;
  onClick?: () => void;
  onCancel?: () => void;
  onError?: (error: any) => void;
  onSuccess?: (data: any) => void | Promise<void>;
  
  // Loading state (for future use - currently handled internally)
  // disabled?: boolean;
}

/**
 * TapPayment Component
 * 
 * Integrates Tap Payments (Benefit Pay) for event registration payments
 * 
 * Backend Requirements:
 * 1. POST /events/:eventId/payments/initiate
 *    - Returns: { publicKey, merchantId, hashString, transactionId, orderId }
 * 
 * 2. POST /events/:eventId/payments/verify
 *    - Body: { transactionId, tapTransactionId, paymentData }
 *    - Verifies payment and updates order status
 * 
 * 3. POST /events/:eventId/payments/webhook (handled by backend)
 *    - Receives Tap webhook notifications
 */
const TapPayment: React.FC<TapPaymentProps> = ({
  amount,
  currency,
  eventId,
  orderId,
  transactionId,
  customer,
  metadata,
  locale = "en",
  edges = "curved",
  debug = false,
  onReady,
  onClick,
  onCancel,
  onError,
  onSuccess,
}) => {
  const [isLoading, setIsLoading] = useState(false);
  const [paymentConfig, setPaymentConfig] = useState<{
    publicKey: string;
    merchantId: string;
    hashString: string;
  } | null>(null);

  // Fetch payment configuration from backend when component mounts
  React.useEffect(() => {
    const fetchPaymentConfig = async () => {
      if (!eventId) {
        console.warn("TapPayment: eventId is required");
        return;
      }

      try {
        setIsLoading(true);
        // Import API function (uncomment when backend is ready)
        // import { initiateTapPayment } from "@/apis/apiHelpers";
        
        // TODO: Replace with actual API call when backend endpoint is ready
        // const response = await initiateTapPayment(eventId, {
        //   amount,
        //   currency,
        //   orderId,
        //   transactionId,
        //   customer,
        //   metadata,
        // });
        // setPaymentConfig({
        //   publicKey: response.data.data.publicKey,
        //   merchantId: response.data.data.merchantId,
        //   hashString: response.data.data.hashString,
        // });
        
        // TEMPORARY: Using placeholder values until backend is ready
        // Remove this block once backend endpoint is implemented
        console.warn("TapPayment: Using placeholder config. Backend endpoint not yet implemented.");
        setPaymentConfig({
          publicKey: "pk_test_xxxx", // Will come from backend
          merchantId: "merchant_xxxx", // Will come from backend
          hashString: "", // Will be generated by backend
        });
      } catch (error) {
        console.error("Failed to initialize payment:", error);
        onError?.(error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchPaymentConfig();
  }, [eventId, amount, currency]);

  const handleSuccess = async (data: any) => {
    try {
      setIsLoading(true);
      
      // Import API function (uncomment when backend is ready)
      // import { verifyTapPayment } from "@/apis/apiHelpers";
      
      // Verify payment with backend
      // TODO: Replace with actual API call when backend endpoint is ready
      // const verifyResponse = await verifyTapPayment(eventId, {
      //   transactionId: transactionId || paymentConfig?.transactionId,
      //   tapTransactionId: data.id,
      //   paymentData: data,
      // });
      // 
      // if (verifyResponse.data.data.success) {
      //   console.log("Payment verified successfully:", verifyResponse.data.data);
      //   await onSuccess?.(data);
      // } else {
      //   throw new Error("Payment verification failed");
      // }
      
      // TEMPORARY: Log success until backend is ready
      console.warn("TapPayment: Payment success callback fired. Backend verification not yet implemented.");
      console.log("Payment data:", data);
      await onSuccess?.(data);
    } catch (error) {
      console.error("Payment verification failed:", error);
      onError?.(error);
    } finally {
      setIsLoading(false);
    }
  };

  // Don't render until payment config is loaded
  if (!paymentConfig || isLoading) {
    return (
      <div className="flex items-center justify-center p-4">
        <div className="text-sm text-gray-500">Loading payment...</div>
      </div>
    );
  }

  return (
    <div className="tap-payment-wrapper">
      <BenefitPayButton
        operator={{
          publicKey: paymentConfig.publicKey,
          hashString: paymentConfig.hashString,
        }}
        debug={debug}
        merchant={{
          id: paymentConfig.merchantId,
        }}
        transaction={{
          amount,
          currency,
          metadata: metadata || {},
        }}
        reference={{
          transaction: transactionId || `txn_${Date.now()}`,
          order: orderId || `ord_${Date.now()}`,
        }}
        customer={
          customer
            ? {
                names: [
                  {
                    lang: locale === "ar" ? Locale.AR : Locale.EN,
                    first: customer.firstName,
                    last: customer.lastName,
                    ...(customer.middleName && { middle: customer.middleName }),
                  },
                ],
                ...(customer.email && {
                  contact: {
                    email: customer.email,
                    ...(customer.phone && {
                      phone: {
                        countryCode: customer.phone.countryCode,
                        number: customer.phone.number,
                      },
                    }),
                  },
                }),
              }
            : undefined
        }
        interface={{
          locale: locale === "ar" ? Locale.AR : Locale.EN,
          edges: edges === "straight" ? Edges.STRAIGHT : Edges.CURVED,
        }}
        post={{
          url: "", // Backend webhook URL (handled server-side)
        }}
        onReady={onReady}
        onClick={onClick}
        onCancel={onCancel}
        onError={(err) => {
          console.error("TapPayment error:", err);
          onError?.(err);
        }}
        onSuccess={handleSuccess}
      />
    </div>
  );
};

export default TapPayment;
